### ISSUE TITLE
USER STORY: Easily manage the site 

### ISSUE THREAD

**Issue by Sndrahel** [Sndrahel/Happy_Feets#16]
As a ** business owner ** I want to be able to ** have access to an admin section **, so that I can ** easily manage the site **

# Tasks:

- [x] Task 1:  Create a superuser
- [x] Task 2: Set up Django admin
- [x] Task 3: Set up all relevant models for admin
