### ISSUE TITLE
USER STORY: Increase the chance of getting returning customers

### ISSUE THREAD

**Issue by Sndrahel** [Sndrahel/Happy_Feets#17]
As a ** business owner ** I want to be able to ** provide easy shopping experience for my customers **, so that I can ** increase the chance of getting returning customers **

# Tasks:

- [x] Task 1:  Fill template with form to add customer details
- [x] Task 2:  Add stripe payment method to view and template
- [x] Task 3: Create webhooks to ensure secure payment and order processing
- [x] Task 4: Create view, url and template for payment successful
